name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04 
    env:
      working-directory: LikeLion-12th-TEAM04-BE/neighbor

    steps: 
    - name: 체크아웃
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
	      with:
        distribution: 'corretto'
        java-version: '17'

    - name: application.yaml 생성
      run: | 
          cd src/main/resources
          echo "${{ secrets.APPLICATION_PROD }}" > ./application-prod.yaml
      working-directory: ${{ env.working-directory }}

    - name: 빌드
      run: |
          chmod +x gradlew
          ./gradlew build -x test
      working-directory: ${{ env.working-directory }}
      shell: bash
