name: CD

on:
  pull_request:
    branches: [ "develop" ]
    
permissions:
  contents: read

jobs:
  deploy-ci:
    runs-on: ubuntu-22.04 
    env:
      working-directory: neighbor
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_LOGIN_ACCESSTOKEN }}

    steps: 
    - name: 체크아웃
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: application-prod.yaml 생성
      run: | 
          cd src/main/resources
          echo "${{ secrets.APPLICATION_PROD }}" > ./application-prod.yaml
      working-directory: ${{ env.working-directory }}

    - name: 빌드
      run: |
          chmod +x gradlew
          ./gradlew build -x test
      working-directory: ${{ env.working-directory }}
      shell: bash
      
    - name: docker build 가능하도록 환경 설정
      uses: docker/setup-buildx-action@v2.9.1

    - name: Log into GitHub container registry
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: sss4920
        password: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Log into Docker registry
      uses: docker/login-action@v3.3.0
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
        password: ${{ secrets.DOCKERHUB_LOGIN_ACCESSTOKEN }}

    - name: docker image 빌드 및 푸시
      run: |
        docker build --platform linux/amd64 -t sss4920/neighbor .
        docker push sss4920/neighbor
      working-directory: ${{ env.working-directory }}

  deploy-cd:      
    needs: deploy-ci
    runs-on: ubuntu-22.04

    steps:    
    - name: 도커 컨테이너 실행
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.RELEASE_SERVER_IP }}
        username: ${{ secrets.RELEASE_SERVER_USER }}
        key: ${{ secrets.RELEASE_SERVER_KEY }}
        run: |
	  cd ~
	  chmod +x deploy.sh
	  ./deploy.sh
